=== m-nied/Servlets/Students.dtd
<!ELEMENT studentrecords (Student*)>
<!ELEMENT Student (fName, lName, status, major)>
<!ELEMENT fName (#PCDATA)>
<!ELEMENT lName (#PCDATA)>
<!ELEMENT status (#PCDATA)>
<!ELEMENT major (#PCDATA)>

=== m-nied/Servlets/Students1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentrecords SYSTEM "Students.dtd">
	<studentrecords>
<Student>
		<fName>april</fName>	
		<lName>may</lName>	
		<status>Provisional</status>	
		<major>Nursing</major>	
	</Student>
	<Student>
		<fName>Keely</fName>	
		<lName>lyons</lName>	
		<status>Full-Time</status>	
		<major>HDFS</major>	
	</Student>
	<Student>
		<fName>Mike</fName>	
		<lName>nied</lName>	
		<status>Part-Time</status>	
		<major>IST</major>	
	</Student>
</studentrecords>

=== m-nied/Servlets/StudentsRegistration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentrecords SYSTEM "Students.dtd">
	<studentrecords>
<Student>
		<fName>Beata</fName>	
		<lName>Nied</lName>	
		<status>Provisional</status>	
		<major>Nursing</major>	
	</Student>
	<Student>
		<fName>Keely</fName>	
		<lName>Lyons</lName>	
		<status>Full-Time</status>	
		<major>HDFS</major>	
	</Student>
	<Student>
		<fName>Mike</fName>	
		<lName>Niedzielski</lName>	
		<status>Part-Time</status>	
		<major>IST</major>	
	</Student>
</studentrecords>
